version: "3.8"

services:
  couchbase:
    image: couchbase:community
    ports:
      - "8091-8096:8091-8096" # Couchbase Web Console, REST API, etc.
      - "11210:11210" # Data nodes port (client SDK communication)
    environment:
      - COUCHBASE_ADMIN_USERNAME=admin
      - COUCHBASE_ADMIN_PASSWORD=password
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8091/pools"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - couchbase_data:/opt/couchbase/var
    networks:
      - backend

  myapp:
    build:
      context: .
      dockerfile: Dockerfile # Optional if it's just "Dockerfile"
    depends_on:
      couchbase:
        condition: service_healthy
    environment:
      - COUCHBASE_HOST=couchbase
      - COUCHBASE_USER=admin
      - COUCHBASE_PASSWORD=password
    ports:
      - "3000:3000" # Change if your app uses another port
    networks:
      - backend

volumes:
  couchbase_data:

networks:
  backend:
