interface CountryCode {
    name: string;
    dial_code: string;
    code: string;
  }
  
  export const countryCodes: CountryCode[] = [
    { "name": "Afghanistan", "dial_code": "+93", "code": "AF" },
    { "name": "Albania", "dial_code": "+355", "code": "AL" },
    { "name": "Algeria", "dial_code": "+213", "code": "DZ" },
    { "name": "Andorra", "dial_code": "+376", "code": "AD" },
    { "name": "Angola", "dial_code": "+244", "code": "AO" },
    { "name": "Antigua and Barbuda", "dial_code": "+1-268", "code": "AG" },
    { "name": "Argentina", "dial_code": "+54", "code": "AR" },
    { "name": "Armenia", "dial_code": "+374", "code": "AM" },
    { "name": "Australia", "dial_code": "+61", "code": "AU" },
    { "name": "Austria", "dial_code": "+43", "code": "AT" },
    { "name": "Azerbaijan", "dial_code": "+994", "code": "AZ" },
    { "name": "Bahamas", "dial_code": "+1-242", "code": "BS" },
    { "name": "Bahrain", "dial_code": "+973", "code": "BH" },
    { "name": "Bangladesh", "dial_code": "+880", "code": "BD" },
    { "name": "Barbados", "dial_code": "+1-246", "code": "BB" },
    { "name": "Belarus", "dial_code": "+375", "code": "BY" },
    { "name": "Belgium", "dial_code": "+32", "code": "BE" },
    { "name": "Belize", "dial_code": "+501", "code": "BZ" },
    { "name": "Benin", "dial_code": "+229", "code": "BJ" },
    { "name": "Bhutan", "dial_code": "+975", "code": "BT" },
    { "name": "Bolivia", "dial_code": "+591", "code": "BO" },
    { "name": "Bosnia and Herzegovina", "dial_code": "+387", "code": "BA" },
    { "name": "Botswana", "dial_code": "+267", "code": "BW" },
    { "name": "Brazil", "dial_code": "+55", "code": "BR" },
    { "name": "Brunei", "dial_code": "+673", "code": "BN" },
    { "name": "Bulgaria", "dial_code": "+359", "code": "BG" },
    { "name": "Burkina Faso", "dial_code": "+226", "code": "BF" },
    { "name": "Burundi", "dial_code": "+257", "code": "BI" },
    { "name": "Cabo Verde", "dial_code": "+238", "code": "CV" },
    { "name": "Cambodia", "dial_code": "+855", "code": "KH" },
    { "name": "Cameroon", "dial_code": "+237", "code": "CM" },
    { "name": "Canada", "dial_code": "+1", "code": "CA" },
    { "name": "Central African Republic", "dial_code": "+236", "code": "CF" },
    { "name": "Chad", "dial_code": "+235", "code": "TD" },
    { "name": "Chile", "dial_code": "+56", "code": "CL" },
    { "name": "China", "dial_code": "+86", "code": "CN" },
    { "name": "Colombia", "dial_code": "+57", "code": "CO" },
    { "name": "Comoros", "dial_code": "+269", "code": "KM" },
    { "name": "Congo (Congo-Brazzaville)", "dial_code": "+242", "code": "CG" },
    { "name": "Congo (Democratic Republic)", "dial_code": "+243", "code": "CD" },
    { "name": "Costa Rica", "dial_code": "+506", "code": "CR" },
    { "name": "Croatia", "dial_code": "+385", "code": "HR" },
    { "name": "Cuba", "dial_code": "+53", "code": "CU" },
    { "name": "Cyprus", "dial_code": "+357", "code": "CY" },
    { "name": "Czech Republic", "dial_code": "+420", "code": "CZ" },
    { "name": "Denmark", "dial_code": "+45", "code": "DK" },
    { "name": "Djibouti", "dial_code": "+253", "code": "DJ" },
    { "name": "Dominica", "dial_code": "+1-767", "code": "DM" },
    { "name": "Dominican Republic", "dial_code": "+1-809", "code": "DO" },
    { "name": "Ecuador", "dial_code": "+593", "code": "EC" },
    { "name": "Egypt", "dial_code": "+20", "code": "EG" },
    { "name": "El Salvador", "dial_code": "+503", "code": "SV" },
    { "name": "Equatorial Guinea", "dial_code": "+240", "code": "GQ" },
    { "name": "Eritrea", "dial_code": "+291", "code": "ER" },
    { "name": "Estonia", "dial_code": "+372", "code": "EE" },
    { "name": "Eswatini", "dial_code": "+268", "code": "SZ" },
    { "name": "Ethiopia", "dial_code": "+251", "code": "ET" },
    { "name": "Fiji", "dial_code": "+679", "code": "FJ" },
    { "name": "Finland", "dial_code": "+358", "code": "FI" },
    { "name": "France", "dial_code": "+33", "code": "FR" },
    { "name": "Gabon", "dial_code": "+241", "code": "GA" },
    { "name": "Gambia", "dial_code": "+220", "code": "GM" },
    { "name": "Georgia", "dial_code": "+995", "code": "GE" },
    { "name": "Germany", "dial_code": "+49", "code": "DE" },
    { "name": "Ghana", "dial_code": "+233", "code": "GH" },
    { "name": "Greece", "dial_code": "+30", "code": "GR" },
    { "name": "Grenada", "dial_code": "+1-473", "code": "GD" },
    { "name": "Guatemala", "dial_code": "+502", "code": "GT" },
    { "name": "Guinea", "dial_code": "+224", "code": "GN" },
    { "name": "Guinea-Bissau", "dial_code": "+245", "code": "GW" },
    { "name": "Guyana", "dial_code": "+592", "code": "GY" },
    { "name": "Haiti", "dial_code": "+509", "code": "HT" },
    { "name": "Honduras", "dial_code": "+504", "code": "HN" },
    { "name": "Hungary", "dial_code": "+36", "code": "HU" },
    { "name": "Iceland", "dial_code": "+354", "code": "IS" },
    { "name": "India", "dial_code": "+91", "code": "IN" },
    { "name": "Indonesia", "dial_code": "+62", "code": "ID" },
    { "name": "Iran", "dial_code": "+98", "code": "IR" },
    { "name": "Iraq", "dial_code": "+964", "code": "IQ" },
    { "name": "Ireland", "dial_code": "+353", "code": "IE" },
    { "name": "Israel", "dial_code": "+972", "code": "IL" },
    { "name": "Italy", "dial_code": "+39", "code": "IT" },
    { "name": "Jamaica", "dial_code": "+1-876", "code": "JM" },
    { "name": "Japan", "dial_code": "+81", "code": "JP" },
    { "name": "Jordan", "dial_code": "+962", "code": "JO" },
    { "name": "Kazakhstan", "dial_code": "+7", "code": "KZ" },
    { "name": "Kenya", "dial_code": "+254", "code": "KE" },
    { "name": "Kiribati", "dial_code": "+686", "code": "KI" },
    { "name": "Korea (North)", "dial_code": "+850", "code": "KP" },
    { "name": "Korea (South)", "dial_code": "+82", "code": "KR" },
    { "name": "Kuwait", "dial_code": "+965", "code": "KW" },
    { "name": "Kyrgyzstan", "dial_code": "+996", "code": "KG" }
  ];  